version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: miniledger-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: miniledger
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: miniledger-rabbitmq
    restart: unless-stopped
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672'
      - '15672:15672'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miniledger-backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: postgres://user:password@db:5432/miniledger
      RABBITMQ_URL: amqp://user:password@rabbitmq:5672

volumes:
  db-data:
